"""
Paper Trading module for the Kalshi Netflix Weekend Effect strategy.

Provides a lightweight ledger that records trading signals generated by the
strategy, pairs them with real outcomes once Netflix publishes the weekly
chart, and tracks running performance metrics.  All state is persisted to a
JSON file so paper trading survives restarts.

Phase 2 Usage
-------------
1. Each weekend, the strategy generates a signal (predicted #1 show).
2. Call :meth:`PaperTrader.record_signal` with the signal details.
3. On Tuesday (after Netflix releases rankings), call
   :meth:`PaperTrader.record_outcome` to record the actual winner.
4. View running stats with :meth:`PaperTrader.get_performance_summary`.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import config as cfg


class PaperTrader:
    """Record and evaluate paper trades for the Weekend Effect strategy.

    Parameters
    ----------
    initial_bankroll : float
        Starting simulated bankroll in dollars.
    log_file : str | Path
        Path to the JSON file used for persistence.
    """

    def __init__(
        self,
        initial_bankroll: float = 100.0,
        log_file: str | Path = "data/paper_trades.json",
    ) -> None:
        self.initial_bankroll: float = initial_bankroll
        self.bankroll: float = initial_bankroll
        self.log_file: Path = Path(log_file)
        self.trades: List[Dict[str, Any]] = []
        self._load_if_exists()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def record_signal(
        self,
        date: str,
        signal: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Record a new trading signal generated by the strategy.

        Parameters
        ----------
        date : str
            ISO-format date string (e.g. ``"2026-07-05"``).
        signal : dict
            Must include at minimum:
            - ``predicted_winner`` (str): title predicted to be #1
            - ``confidence`` (float): model confidence 0-1
            - ``entry_price`` (float): price per contract (e.g. 0.55)

            Additional keys (e.g. ``weekend_rank``, ``weekday_rank``) are
            preserved as metadata.

        Returns
        -------
        dict
            The full trade record that was created.
        """
        confidence = signal.get("confidence", 0.0)
        entry_price = signal.get("entry_price", 0.55)
        side = signal.get("side", "yes")  # "yes" = back predicted winner; "no" = fade target
        target_title = signal.get("target_title") or signal.get("predicted_winner", "")

        # Fractional Kelly (config.KELLY_FRACTION, default quarter-Kelly)
        b = (1 - entry_price) / entry_price if entry_price > 0 else 1
        q = 1 - confidence
        kelly_f = max((b * confidence - q) / b, 0.0) * cfg.KELLY_FRACTION
        bet_size = self.bankroll * kelly_f
        contracts = int(bet_size / entry_price) if entry_price > 0 else 0

        trade: Dict[str, Any] = {
            "id": len(self.trades) + 1,
            "signal_date": date,
            "recorded_at": datetime.now(timezone.utc).isoformat(),
            "status": "open",
            "predicted_winner": signal.get("predicted_winner", ""),
            "side": side,
            "target_title": target_title,
            "confidence": confidence,
            "entry_price": entry_price,
            "bet_size": bet_size,
            "contracts": contracts,
            "signal_meta": {
                k: v
                for k, v in signal.items()
                if k not in (
                    "predicted_winner", "confidence", "entry_price",
                    "side", "target_title",
                )
            },
            # Outcome fields — filled in later
            "actual_winner": None,
            "won": None,
            "pnl": None,
            "resolved_at": None,
        }
        self.trades.append(trade)
        self.save()
        return trade

    def record_outcome(
        self,
        date: str,
        actual_winner: str,
    ) -> List[Dict[str, Any]]:
        """Resolve all open trades for *date* with the actual weekly winner.

        Parameters
        ----------
        date : str
            ISO-format date of the original signal (used to match trades).
        actual_winner : str
            The show that actually topped the Netflix weekly chart.

        Returns
        -------
        list[dict]
            The resolved trade records.
        """
        resolved: List[Dict[str, Any]] = []
        for trade in self.trades:
            if trade["signal_date"] == date and trade["status"] == "open":
                side = trade.get("side", "yes")
                target = (
                    trade.get("target_title") or trade["predicted_winner"]
                ).strip().lower()
                target_won = target == actual_winner.strip().lower()
                # YES pays when the target wins; NO pays when it loses.
                won = target_won if side == "yes" else not target_won


                contracts = trade.get("contracts", 0)
                price = trade.get("entry_price", 0.55)
                
                if won:
                    pnl = contracts * (1 - price)
                else:
                    pnl = -contracts * price

                trade["actual_winner"] = actual_winner
                trade["won"] = won
                trade["pnl"] = pnl
                trade["status"] = "resolved"
                trade["resolved_at"] = datetime.now(timezone.utc).isoformat()

                self.bankroll += pnl
                resolved.append(trade)

        self.save()
        return resolved

    def get_calibrated_confidence(self, raw_confidence: float) -> float:
        """Shrink a hand-tuned confidence toward the ledger's empirical win rate.

        Looks at resolved trades whose recorded confidence was within
        ``config.CALIBRATION_BUCKET_WIDTH`` of *raw_confidence*. With at
        least ``config.CALIBRATION_MIN_SAMPLES`` such trades, returns a
        shrinkage blend where the raw confidence counts as
        ``config.CALIBRATION_PRIOR_WEIGHT`` pseudo-trades. With too little
        history the raw confidence is returned unchanged.
        """
        similar = [
            t for t in self.get_trade_history()
            if abs(t.get("confidence", 0.0) - raw_confidence)
            <= cfg.CALIBRATION_BUCKET_WIDTH
        ]
        n = len(similar)
        if n < cfg.CALIBRATION_MIN_SAMPLES:
            return raw_confidence
        empirical = sum(1 for t in similar if t["won"]) / n
        k = cfg.CALIBRATION_PRIOR_WEIGHT
        blended = (empirical * n + raw_confidence * k) / (n + k)
        return round(min(max(blended, cfg.CONFIDENCE_FLOOR), cfg.CONFIDENCE_CEILING), 4)

    def get_open_positions(self) -> List[Dict[str, Any]]:
        """Return all trades that are still waiting for resolution."""
        return [t for t in self.trades if t["status"] == "open"]

    def get_trade_history(self) -> List[Dict[str, Any]]:
        """Return all resolved (completed) trades."""
        return [t for t in self.trades if t["status"] == "resolved"]

    def get_performance_summary(self) -> Dict[str, Any]:
        """Compute running performance statistics.

        Returns
        -------
        dict
            Keys include ``total_trades``, ``wins``, ``losses``,
            ``win_rate``, ``total_pnl``, ``bankroll``, ``roi``,
            ``avg_pnl_per_trade``, ``best_trade``, ``worst_trade``.
        """
        resolved = self.get_trade_history()
        if not resolved:
            return {
                "total_trades": 0,
                "wins": 0,
                "losses": 0,
                "win_rate": 0.0,
                "total_pnl": 0.0,
                "bankroll": self.bankroll,
                "roi": 0.0,
                "avg_pnl_per_trade": 0.0,
                "best_trade": 0.0,
                "worst_trade": 0.0,
            }

        wins = sum(1 for t in resolved if t["won"])
        losses = len(resolved) - wins
        pnls = [t["pnl"] for t in resolved]
        total_pnl = sum(pnls)

        return {
            "total_trades": len(resolved),
            "wins": wins,
            "losses": losses,
            "win_rate": wins / len(resolved) if resolved else 0.0,
            "total_pnl": round(total_pnl, 2),
            "bankroll": round(self.bankroll, 2),
            "roi": round(total_pnl / self.initial_bankroll * 100, 2),
            "avg_pnl_per_trade": round(total_pnl / len(resolved), 2),
            "best_trade": round(max(pnls), 2),
            "worst_trade": round(min(pnls), 2),
        }

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def save(self) -> None:
        """Persist the current state to the JSON log file."""
        self.log_file.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "initial_bankroll": self.initial_bankroll,
            "bankroll": round(self.bankroll, 4),
            "trades": self.trades,
        }
        with open(self.log_file, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2, default=str)

    def load(self) -> None:
        """Load state from the JSON log file.

        Raises
        ------
        FileNotFoundError
            If the log file does not exist.
        """
        with open(self.log_file, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        self.initial_bankroll = data.get("initial_bankroll", self.initial_bankroll)
        self.bankroll = data.get("bankroll", self.initial_bankroll)
        self.trades = data.get("trades", [])

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _load_if_exists(self) -> None:
        """Silently load persisted state if the file exists."""
        if self.log_file.exists():
            try:
                self.load()
            except (json.JSONDecodeError, KeyError) as exc:
                print(f"[paper_trader] Warning: could not load {self.log_file}: {exc}")

    def __repr__(self) -> str:
        summary = self.get_performance_summary()
        return (
            f"PaperTrader(bankroll=${summary['bankroll']:.2f}, "
            f"trades={summary['total_trades']}, "
            f"win_rate={summary['win_rate']:.1%})"
        )
